export enum PlatformCategory {
  CONSOLE = 'CONSOLE',
  ARCADE = 'ARCADE',
  PLATFORM = 'PLATFORM',
  OPERATION_SYSTEM = 'OPERATION_SYSTEM',
  PORTABLE_CONSOLE = 'PORTABLE_CONSOLE',
  COMPUTER = 'COMPUTER'
}
